### ISSUE TITLE
Update to use aws/aws-sdk-php-zf2 v2

### ISSUE THREAD

**Issue by amdopsworks** [juriansluiman/SlmQueueSqs#28]
aws/aws-sdk-php-zf2 has released v2, which uses v3 of the AWS SDK.

The composer.json forces v1.* of aws/aws-sdk-php-zf2.

**Comment by bakura10** [comment]
Yes, because v2 of SDK uses v3 of AWS SDK, which will break compatibility with SlmQueueSqs. We'll likely need ot update SlmQueueSqs to update to this new dependency

**Comment by bakura10** [comment]
Just to let you know that I'm planning to do that this week ;)

**Comment by antonycox** [comment]
Hi. Any update on when this dependency update might be resolved?

**Comment by bakura10** [comment]
I've just now tag v0.5.0 that supports the v3 of SDK :).
