### ISSUE TITLE
Add cache

### ISSUE THREAD

**Issue by iam-merlin** [juriansluiman/SlmQueueSqs#31]
Hi,

I like what is done in `SqsQueue.php` with the ability to fetch on AWS directly the queue url. This is interesting because if you create dynamically your env you don't want to create a specific config file each time the env is recreated.

This call is not caching, do you think it's a good idea to add a cache service in config? (can do it ofc... quite simple)

ping @bakura10

**Comment by bakura10** [comment]
Hi,

I think that it's a lot of work for nothing. Typically, you'll set the URL directly of your queues: https://github.com/juriansluiman/SlmQueueSqs#configuring-queues

When that's the case, no call will be made to AWS. Of course, if you are dynamically creating queues, and only reference them by name, that could be useful, but I think that there are a limit in AWS on how many queues you could create (so I'm not sure that would be such a nice idea), and you could always create your queues, cache the URL in your DB, and pass it directly when constructing your queue.

I'd prefer not to introduce an additional dependency to a cache lib just for that :).
