### ISSUE TITLE
Basic FIFO support

### ISSUE THREAD

**Issue by OctavianParalescu** [juriansluiman/SlmQueueSqs#45]
Currently FIFO is not supported at all and it cannot be supported using the current class design.

I created a basic modification of the package to support FIFO queues but it definitely needs some enhancements, at least on the testing part:
https://github.com/OctavianParalescu/SlmQueueSqs/commit/c11e1107c2b0277839d018eec40da1e870db0b89

What are your thoughts on this one?

**Comment by basz** [comment]
Not much as I don't use SQS. But it I think it would be great if we could support it.

**Comment by basz** [comment]
done, thanks @tobo-pl @neeckeloo
